name: CI
on:
  push:
    branches:
      - master
      - new-workflow-llvm
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@llvm
    with:
      test-command: |
        env NIMLANG=c nimble test
        nimble install chronos
        env NIMLANG=c nimble testChronos || true
